### ISSUE TITLE
About  dynamic alignment

### ISSUE THREAD

**Issue by weiyithu** [jiah-cloud/Align3R#4]
Thanks for your great work! I wonder whether this method can align the dynamic parts of different frames into a single frame, or if it only predicts the dynamic parts within the current frame?

**Comment by jiah-cloud** [comment]
Yes, our method can align the dynamic parts of different frames into a single frame. Following DUSt3R, we input two frames into the network and predict the point maps in the first frame's coordinate system.

**Comment by weiyithu** [comment]
Hi, I visualize the pair-wise results from https://github.com/jiah-cloud/Align3R/blob/5958b8aa83fb9ce21e64c659a1cf7035cf2a47ae/tool/demo.py#L144. However, I find the dynamic parts of two images are not aligned. 
Output point cloud:  
![img1](https://github.com/user-attachments/assets/725e7df0-68f4-497e-a5fa-73cf60e8babd)
Input pair images:
![img2](https://github.com/user-attachments/assets/be02538c-2bc0-4bc9-9b94-8a299d619d92)
![img3](https://github.com/user-attachments/assets/f263425b-eec3-4382-967e-36dc5c0f9439)

**Comment by JUGGHM** [comment]
> Hi, I visualize the pair-wise results from
> 
> https://github.com/jiah-cloud/Align3R/blob/5958b8aa83fb9ce21e64c659a1cf7035cf2a47ae/tool/demo.py#L144
> 
> . However, I find the dynamic parts of two images are not aligned.
> Output point cloud:
> ![img1](https://private-user-images.githubusercontent.com/32617425/394217797-725e7df0-68f4-497e-a5fa-73cf60e8babd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4Mzc5NTUsIm5iZiI6MTczMzgzNzY1NSwicGF0aCI6Ii8zMjYxNzQyNS8zOTQyMTc3OTctNzI1ZTdkZjAtNjhmNC00OTdlLWE1ZmEtNzNjZjYwZThiYWJkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDEzMzQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMmM0MWI1YWEwMTU3NzhjODJmZDBlNWIzNzQ3MmUwZWRkOTU2ODYxNmMwMGU3NDVjZGYyMDc1NTFjNTY3Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Sw6QitAoMG_dLeiDU7vxjrks1Ab22DE9Idmp60ntsog)
> Input pair images:
> ![img2](https://private-user-images.githubusercontent.com/32617425/394219064-be02538c-2bc0-4bc9-9b94-8a299d619d92.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4Mzc5NTUsIm5iZiI6MTczMzgzNzY1NSwicGF0aCI6Ii8zMjYxNzQyNS8zOTQyMTkwNjQtYmUwMjUzOGMtMmJjMC00YmM5LTliOTQtOGEyOTlkNjE5ZDkyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDEzMzQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMTJkYmVmYWNhYjg5MDE5ZDA2NzZiNTNkODZkYmIzMDZlODFmYWY2ODliNmNiODcxODMzZWJlNjAzMmUyODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.i4I8SDILdl1RAvc5TwmLs3tktZ1sc6oQvOz0Faz2tpc)
> ![img3](https://private-user-images.githubusercontent.com/32617425/394219351-f263425b-eec3-4382-967e-36dc5c0f9439.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4Mzc5NTUsIm5iZiI6MTczMzgzNzY1NSwicGF0aCI6Ii8zMjYxNzQyNS8zOTQyMTkzNTEtZjI2MzQyNWItZWVjMy00MzgyLTk2N2UtMzZkYzVjMGY5NDM5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDEzMzQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZWFmMjBmN2I0MzRkMjRiZDk1ZjZjZWFhZjNlNzhjOWE5MTZiNGYyZjczYTFkZDQ5YjE3ZDlkZTg2MGQwYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0ZWbN-Y4HYnOjZ8SB7pHq5jzhwJq94kFdINCR1WxZdA)

Why should they be aligned?

**Comment by jiah-cloud** [comment]
Sorry, I misunderstood your meaning. Our method, Align3R, aligns the dynamic parts of two images into the same coordinate system, but it does not align to the same timestep.

**Comment by weiyithu** [comment]
> Sorry, I misunderstood your meaning. Our method, Align3R, aligns the dynamic parts of two images into the same coordinate system, but it does not align to the same timestep.

Oh i get it. By the way, whether we can align to the same timestep with dynamic training datasets such as Sceneflow and PointOdyssey?

**Comment by jiah-cloud** [comment]
You should check whether these datasets have the 2D flow annotations and then retrain the model.

**Comment by weiyithu** [comment]
Thanks for your response！
