### ISSUE TITLE
NotImplementedError: Only MP4 video and JPEG folder are supported at this moment

### ISSUE THREAD

**Issue by kexul** [jiah-cloud/Align3R#6]
```
Align3R/dust3r/cloud_opt_flow/optimizer.py", line 254, in refine_motion_mask_w_sam2
    inference_state = predictor.init_state(video_path=frame_tensors)
```
Hi, I encountered this error when inferencing using `demo.sh`.

**Comment by kexul** [comment]
It seems like a previously pip installed sam2 in my environment is used instead of the sam2 in the third-party folder...

**Comment by jiah-cloud** [comment]
Could you try the following commands to see if the issue is resolved?
```bash
cd third_party/sam2
pip install -e .
```

**Comment by kexul** [comment]
Thanks for your suggestion!
I've solved it by insert the path of sam2 befor importing:

```
import sys
local_path = 'Align3R/third_party/sam2'
sys.path.insert(0, local_path)
```
