### ISSUE TITLE
Where to find camera position parameters?

### ISSUE THREAD

**Issue by RafailFridman** [jiah-cloud/Align3R#7]
Hi, thank you for your work!

I tried running your demo script on my video but could not find the camera parameters output. I see files for camera intrinsic and depth maps but don't see extrinsics - R and T for each frame.

Could you please point me to what I should do to get them?

Thanks in advance

**Comment by jiah-cloud** [comment]
You can use the following code to get the camera poses:
```python
poses = scene.save_tum_poses(f'{save_folder}/pred_traj.txt')
```
Thank you.

**Comment by RafailFridman** [comment]
Thank you!

**Comment by Chuan-10** [comment]
Hi @jiah-cloud, thanks for your amazing work!

I tried running the demo script on my video and used the code above to extract the camera poses. However, I noticed an issue: the number of camera poses in pred_traj.txt doesn’t match the number of frames in my video. For instance, my video has 100 frames, but I only got 3 poses.

Any ideas on what might be causing this? Thanks in advance!
